### ISSUE TITLE
Redis.push command issues

### ISSUE THREAD

**Issue by Judical** [zencashio/z-nomp#150]
Only thing I have left to get payments working. Please let me know what would normally cause this error;

2017-05-30 15:55:01 [Pool]      [komodo] (Thread 4) Block notification via RPC polling
/home/judical/kmd-nomp/libs/shareProcessor.js:89
           redisCommands.push(['sadd', coin + ':blocksPending', [shareData.blockHash, shareData.txHash, shareData.height, shareData.worker, Round.Reward, dateNow].join(':')]);
                                                                                                                                            ^

ReferenceError: Round is not defined
   at module.exports.handleShare (/home/judical/kmd-nomp/libs/shareProcessor.js:89:142)
   at Object.handlers.share (/home/judical/kmd-nomp/libs/poolWorker.js:159:32)
   at pool.<anonymous> (/home/judical/kmd-nomp/libs/poolWorker.js:199:22)
   at emitThree (events.js:116:13)
   at pool.emit (events.js:197:7)
   at emitShare (/home/judical/kmd-nomp/node_modules/stratum-pool/lib/pool.js:308:23)
   at /home/judical/kmd-nomp/node_modules/stratum-pool/lib/pool.js:331:29
   at /home/judical/kmd-nomp/node_modules/stratum-pool/lib/pool.js:614:25
   at /home/judical/kmd-nomp/node_modules/stratum-pool/lib/daemon.js:175:17
   at /home/judical/kmd-nomp/node_modules/async/dist/async.js:421:16
2017-05-30 15:55:01 [Pool]      [komodo] (Thread 7) Block notification via RPC polling
2017-05-30 15:55:01 [Master]    [PoolSpawner] Fork 2 died, spawning replacement worker...
2017-05-30 15:55:01 [Pool]      [komodo] (Thread 5) Block notification via blocknotify script

**Comment by DeckerSU** [comment]
Are you setup kmd-nomp, instead of z-nomp, right? I have the same problem on kmd-nomp (Round is not defined) with payment processing turned off. Please, let me know if you find a solution.

**Comment by aayanl** [comment]
use z-nomp instead, it has KMD support

**Comment by DeckerSU** [comment]
Thx for reply. And the last question, is the Payment processing works correctly on latest z-nomp sources with Komodo Coin?

**Comment by aayanl** [comment]
Yes
